### ISSUE TITLE
Debug Task1

### ISSUE THREAD

**Issue by prateek2105** [opencodeiiita/CodeDigger#1]
[Debug_Task1.txt](https://github.com/user-attachments/files/18141556/Debug_Task1.txt)
[Debug_Solution1.txt](https://github.com/user-attachments/files/18141565/Debug_Solution1.txt)

- **Debugging Task:** Read the Problem Statement in Debug_Task1.txt and Debug the code in Debug_Solution1.cpp attached with this issue.
- **Folder Creation:** Create a Task 1 folder within Debugs-and-Optimizations. Inside Task 1, add:
       **explanation.txt:** Explain why the given submission failed.
       **solution.cpp:** Correct the code without a complete rewrite.

- Provide a **testcase** at the top of explanation.txt on which the code in Debug_Solution1.cpp fails.

- **Correction Approach:** Make necessary code corrections, you may change the code as you need.

- **Deadline:** Complete the task within one day to avoid reassignment
- **Pull Request (PR) Conditions:** PRs with incorrect answers won’t be merged; the issue will be reassigned.

**Comment by Sarvesh0955** [comment]
claim

**Comment by apexcoder007** [comment]
claim

**Comment by spotnewmoon** [comment]
Claim

**Comment by Ada-kr** [comment]
claim

**Comment by ashutosh-iiita0** [comment]
Claim

**Comment by official-ashutosh** [comment]
Claim

**Comment by rndastech** [comment]
claim

**Comment by ayush-patel1** [comment]
claim

**Comment by ayush-patel1** [comment]
claim

**Comment by sanjitha006** [comment]
claim

**Comment by ayush-patel1** [comment]
claim

**Comment by rishabhking** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by rishabhking** [comment]
Task completed by @Sarvesh0955
