### ISSUE TITLE
Task2_Distant-Friends

### ISSUE THREAD

**Issue by Sparshga** [opencodeiiita/CodeDigger#96]
Steps to solve this problem successfully

-make a file (.cpp or any programming code) containing your code in [Task2_Distant-Friends](https://github.com/opencodeiiita/CodeDigger/tree/main/Tasks/task-2-Distant-Friends) folder in Tasks.

-You have 1 day until the spy gets bored with you and assigns the task to someone else.

-Your PR will not be merged if it contains the Wrong Answer.

**Comment by sanjitha006** [comment]
claim
